# Set TERM environment variable
.env:
  TERM: 'xterm-256color'

# Window configuration
window:
  padding:
    x: 10
    y: 8
  decorations: none
  startup_mode: Maximized
  title: Terminal
  opacity: 1.0

scrolling:
  history: 0

# Font configuration
font:
  normal:
    family: Source Code Pro for Powerline
    style: Regular
  bold:
    family: Source Code Pro for Powerline
    style: Bold
  italic:
    family: Source Code Pro for Powerline
    style: Italic
  bold_italic:
    family: Source Code Pro for Powerline
    style: Bold Italic
  size: 16.0
  use_thin_strokes: true

selection:
  save_to_clipboard: false

shell:
  program: /bin/zsh
  args:
    - --login
    - -c
    - "tmux attach -t ws || tmux new -s ws"

hints:
  enabled:
    # Disable opening links when clicked
    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: xdg-open
      post_processing: true
      mouse:
        enabled: false
        mods: None
