# Set TERM environment variable
.env:
  TERM: 'xterm-256color'
  LANG: "en_US.UTF-8"
  LC_CTYPE: "en_US.UTF-8"

# Window configuration
window:
  padding:
    x: 10
    y: 8
  decorations: None
  startup_mode: Maximized
  title: Terminal
  opacity: 1

scrolling:
  history: 0

# Font configuration
font:
  normal:
    family: Hack Nerd Font
    style: Regular
  bold:
    family: Hack Nerd Font
    style: Bold
  italic:
    family: Hack Nerd Font
    style: Italic
  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic
  size: 11.0

colors:
  primary:
    background: '#262626'
    foreground: '#AFAFAF'

selection:
  save_to_clipboard: false

hints:
  enabled:
    # Disable opening links when clicked
    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
             [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: xdg-open
      post_processing: true
      mouse:
        enabled: false
        mods: None
