# Window configuration
window:
  padding:
    x: 10
    y: 8
  decorations: none
  startup_mode: Maximized
  title: Terminal

scrolling:
  history: 0

background_opacity: 1.0

# Font configuration
font:
  normal:
    family: Source Code Pro for Powerline
    style: Regular
  bold:
    family: Source Code Pro for Powerline
    style: Bold
  italic:
    family: Source Code Pro for Powerline
    style: Italic
  bold_italic:
    family: Source Code Pro for Powerline
    style: Bold Italic
  size: 16.0
  use_thin_strokes: true

# Colors (Material Theme)
colors:
  # Default colors
  primary:
    background: '0x1e282d'
    foreground: '0xc4c7d1'

  # Normal colors
  normal:
    black:   '0x666666'
    red:     '0xeb606b'
    green:   '0xc3e88d'
    yellow:  '0xf7eb95'
    blue:    '0x80cbc4'
    magenta: '0xff2f90'
    cyan:    '0xaeddff'
    white:   '0xffffff'

  # Bright colors
  bright:
    black:   '0xa1a1a1'
    red:     '0xeb606b'
    green:   '0xc3e88d'
    yellow:  '0xf7eb95'
    blue:    '0x7dc6bf'
    magenta: '0x6c71c4'
    cyan:    '0x35434d'
    white:   '0xffffff'

selection:
  save_to_clipboard: false

shell:
  program: /bin/zsh
  args:
    - --login
    - -c
    - "tmux attach -t ws || tmux new -s ws"

