# Window configuration
window:
  padding:
    x: 10
    y: 8
  decorations: none
  startup_mode: Maximized
  title: Terminal

scrolling:
  history: 0

background_opacity: 1.0

# Font configuration
font:
  normal:
    family: Source Code Pro for Powerline
    style: Regular
  bold:
    family: Source Code Pro for Powerline
    style: Bold
  italic:
    family: Source Code Pro for Powerline
    style: Italic
  bold_italic:
    family: Source Code Pro for Powerline
    style: Bold Italic
  size: 16.0
  use_thin_strokes: true

selection:
  save_to_clipboard: false

shell:
  program: /bin/zsh
  args:
    - --login
    - -c
    - "tmux attach -t ws || tmux new -s ws"

